import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { api } from '@/lib/api'
import { useAuthStore } from '@/store/auth'
import { Card, CardContent } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Modal } from '@/components/ui/Modal'
import { TrendingUp, TrendingDown, Wallet, Plus, X, Pencil, Lock, Settings, Info, ExternalLink } from 'lucide-react'
import { Skeleton } from '@/components/ui/Skeleton'

interface Transaction {
  id: string
  type: 'INCOME' | 'EXPENSE'
  category: string
  amount: number
  description: string
  reference: string | null
  date: string
  notes: string | null
  autoGenerated: boolean
  sourceRef: string | null
  member: { fullName: string; nickname: string | null; memberNumber: string | null } | null
}

interface TreasuryData {
  transactions: Transaction[]
  initialBalance: number
  totalIncome: number
  totalExpense: number
  balance: number
}

const INCOME_CATEGORIES  = ['Quotas', 'Multas', 'Patrocínio', 'Evento', 'Doação', 'Outro']
const EXPENSE_CATEGORIES = ['Equipamento', 'Combustível', 'Alojamento', 'Refeições', 'Manutenção', 'Administrativo', 'Evento', 'Outro']

const TYPE_LABELS: Record<string, string> = { INCOME: 'Receita', EXPENSE: 'Despesa' }
const TYPE_COLORS: Record<string, string> = {
  INCOME:  'bg-green-100 text-green-700',
  EXPENSE: 'bg-red-100 text-red-700',
}

function fmt(d: string) { return new Date(d).toLocaleDateString('pt-AO') }
function fmtKz(n: number) { return n.toLocaleString('pt-AO') + ' Kz' }

const currentYear = new Date().getFullYear()
const YEARS = Array.from({ length: 4 }, (_, i) => currentYear - i)

const emptyForm = {
  type: 'INCOME' as 'INCOME' | 'EXPENSE',
  category: '',
  amount: '',
  description: '',
  reference: '',
  date: new Date().toISOString().slice(0, 10),
  notes: '',
}

export default function Treasury() {
  const qc = useQueryClient()
  const navigate = useNavigate()
  const isPlatformAdmin = useAuthStore(s => s.user?.platformAdmin ?? false)
  const [year, setYear]   = useState(currentYear)
  const [typeF, setTypeF] = useState<'ALL' | 'INCOME' | 'EXPENSE'>('ALL')
  const [showModal, setShowModal]           = useState(false)
  const [showBalanceModal, setShowBalanceModal] = useState(false)
  const [editing, setEditing]               = useState<Transaction | null>(null)
  const [detailTx, setDetailTx]             = useState<Transaction | null>(null)
  const [form, setForm]                     = useState(emptyForm)
  const [balanceInput, setBalanceInput]     = useState('')

  const { data, isLoading } = useQuery<TreasuryData>({
    queryKey: ['treasury', year, typeF],
    queryFn: () => api.get('/treasury', {
      params: { year, ...(typeF !== 'ALL' && { type: typeF }) },
    }).then(r => r.data),
  })

  const transactions = data?.transactions ?? []

  const createMutation = useMutation({
    mutationFn: () => api.post('/treasury', { ...form, amount: parseFloat(form.amount) }).then(r => r.data),
    onSuccess: () => {
      toast.success('Transacção registada')
      qc.invalidateQueries({ queryKey: ['treasury'] })
      closeModal()
    },
    onError: (e: any) => toast.error(e.response?.data?.error ?? 'Erro'),
  })

  const updateMutation = useMutation({
    mutationFn: () => api.patch(`/treasury/${editing!.id}`, { ...form, amount: parseFloat(form.amount) }).then(r => r.data),
    onSuccess: () => {
      toast.success('Transacção actualizada')
      qc.invalidateQueries({ queryKey: ['treasury'] })
      closeModal()
    },
    onError: (e: any) => toast.error(e.response?.data?.error ?? 'Erro'),
  })

  const balanceMutation = useMutation({
    mutationFn: () => api.patch('/treasury/initial-balance', { amount: parseFloat(balanceInput) }).then(r => r.data),
    onSuccess: () => {
      toast.success('Saldo inicial actualizado')
      qc.invalidateQueries({ queryKey: ['treasury'] })
      setShowBalanceModal(false)
    },
    onError: (e: any) => toast.error(e.response?.data?.error ?? 'Erro'),
  })

  function openCreate() {
    setEditing(null)
    setForm(emptyForm)
    setShowModal(true)
  }

  function openEdit(tx: Transaction) {
    setEditing(tx)
    setForm({
      type: tx.type,
      category: tx.category,
      amount: String(tx.amount),
      description: tx.description,
      reference: tx.reference ?? '',
      date: tx.date.slice(0, 10),
      notes: tx.notes ?? '',
    })
    setShowModal(true)
  }

  function closeModal() { setShowModal(false); setEditing(null) }

  function openBalanceModal() {
    setBalanceInput(String(data?.initialBalance ?? 0))
    setShowBalanceModal(true)
  }

  function deleteTx(id: string) {
    if (!confirm('Eliminar esta transacção?')) return
    api.delete(`/treasury/${id}`)
      .then(() => { qc.invalidateQueries({ queryKey: ['treasury'] }); toast.success('Eliminada') })
      .catch((e: any) => toast.error(e.response?.data?.error ?? 'Erro ao eliminar. Verifique se é uma transacção manual.'))
  }

  const categories = form.type === 'INCOME' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES

  return (
    <div className="fade-in space-y-5">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Tesouraria</h1>
          <p className="text-sm text-gray-500 mt-0.5">Receitas e despesas do clube</p>
        </div>
        <Button onClick={openCreate}><Plus size={15} /> Registar movimento</Button>
      </div>

      {/* Filtros */}
      <div className="flex items-center gap-3 flex-wrap">
        <select
          className="border border-gray-200 rounded-xl px-3 py-2 text-sm bg-white"
          value={year} onChange={e => setYear(+e.target.value)}
        >
          {YEARS.map(y => <option key={y} value={y}>{y}</option>)}
        </select>
        <div className="flex bg-gray-100 rounded-xl p-1 gap-1">
          {(['ALL', 'INCOME', 'EXPENSE'] as const).map(f => (
            <button key={f} onClick={() => setTypeF(f)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${typeF === f ? 'bg-white shadow text-gray-900' : 'text-gray-500 hover:text-gray-700'}`}>
              {f === 'ALL' ? 'Todos' : TYPE_LABELS[f]}
            </button>
          ))}
        </div>
      </div>

      {/* Resumo */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {/* Saldo inicial */}
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center justify-between mb-1">
              <div className="flex items-center gap-2">
                <Wallet size={15} className="text-blue-500" />
                <span className="text-xs text-gray-500 font-medium">Saldo inicial</span>
              </div>
              <button onClick={openBalanceModal} className="p-1 text-gray-300 hover:text-gray-600 transition-colors" title="Editar saldo inicial">
                <Settings size={13} />
              </button>
            </div>
            <p className="text-xl font-bold text-blue-600">{fmtKz(data?.initialBalance ?? 0)}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <TrendingUp size={15} className="text-green-600" />
              <span className="text-xs text-gray-500 font-medium">Receitas</span>
            </div>
            <p className="text-xl font-bold text-green-600">{fmtKz(data?.totalIncome ?? 0)}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <TrendingDown size={15} className="text-red-500" />
              <span className="text-xs text-gray-500 font-medium">Despesas</span>
            </div>
            <p className="text-xl font-bold text-red-500">{fmtKz(data?.totalExpense ?? 0)}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="flex items-center gap-2 mb-1">
              <Wallet size={15} className="text-gray-600" />
              <span className="text-xs text-gray-500 font-medium">Saldo total</span>
            </div>
            <p className={`text-xl font-bold ${(data?.balance ?? 0) >= 0 ? 'text-gray-900' : 'text-red-600'}`}>
              {fmtKz(data?.balance ?? 0)}
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Lista */}
      {isLoading ? (
        <Card>
          <CardContent className="pt-0 pb-0">
            <div className="divide-y divide-gray-50">
              {Array.from({ length: 6 }).map((_, i) => (
                <div key={i} className="py-3.5 flex items-center gap-3">
                  <Skeleton className="w-8 h-8 rounded-full flex-shrink-0" />
                  <div className="flex-1 space-y-2">
                    <div className="flex items-center gap-2">
                      <Skeleton className="h-3.5 w-40 rounded" />
                      <Skeleton className="h-5 w-16 rounded-full" />
                    </div>
                    <Skeleton className="h-3 w-24 rounded" />
                  </div>
                  <Skeleton className="h-4 w-20 rounded flex-shrink-0" />
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardContent className="pt-0 pb-0">
            <div className="divide-y divide-gray-50">
              {transactions.map(tx => (
                <div key={tx.id} className="py-3.5 flex items-center gap-3">
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${tx.type === 'INCOME' ? 'bg-green-100' : 'bg-red-100'}`}>
                    {tx.type === 'INCOME'
                      ? <TrendingUp size={14} className="text-green-600" />
                      : <TrendingDown size={14} className="text-red-500" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-sm font-medium text-gray-900 truncate">{tx.description}</span>
                      <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${TYPE_COLORS[tx.type]}`}>{tx.category}</span>
                      {tx.autoGenerated && (
                        <span className="text-xs font-semibold px-2 py-0.5 rounded-full bg-blue-50 text-blue-500 flex items-center gap-1">
                          <Lock size={10} /> Auto
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-gray-400 mt-0.5">
                      {fmt(tx.date)}
                      {tx.reference && ` · Ref: ${tx.reference}`}
                      {tx.member && ` · ${tx.member.nickname ?? tx.member.fullName}`}
                    </p>
                  </div>
                  <div className="flex items-center gap-1 flex-shrink-0">
                    <span className={`text-sm font-bold mr-1 ${tx.type === 'INCOME' ? 'text-green-600' : 'text-red-500'}`}>
                      {tx.type === 'INCOME' ? '+' : '-'}{fmtKz(tx.amount)}
                    </span>
                    {!tx.autoGenerated && (
                      <>
                        <button onClick={() => openEdit(tx)} className="p-1.5 text-gray-300 hover:text-gray-600 transition-colors">
                          <Pencil size={13} />
                        </button>
                        <button onClick={() => deleteTx(tx.id)} className="p-1.5 text-gray-300 hover:text-red-500 transition-colors">
                          <X size={13} />
                        </button>
                      </>
                    )}
                    {tx.autoGenerated && (
                      <>
                        <button onClick={() => setDetailTx(tx)} className="p-1.5 text-gray-300 hover:text-blue-500 transition-colors" title="Ver detalhes">
                          <Info size={13} />
                        </button>
                        {isPlatformAdmin ? (
                          <button onClick={() => deleteTx(tx.id)} className="p-1.5 text-gray-300 hover:text-red-500 transition-colors" title="Eliminar (admin)">
                            <X size={13} />
                          </button>
                        ) : (
                          <div className="w-[26px]" />
                        )}
                      </>
                    )}
                  </div>
                </div>
              ))}
              {transactions.length === 0 && (
                <p className="text-center text-gray-400 text-sm py-12">Sem movimentos registados para {year}.</p>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Modal transacção */}
      <Modal open={showModal} onClose={closeModal} title={editing ? 'Editar transacção' : 'Registar movimento'}>
        <div className="space-y-4">
          <div className="flex bg-gray-100 rounded-xl p-1 gap-1">
            {(['INCOME', 'EXPENSE'] as const).map(t => (
              <button key={t} onClick={() => setForm(f => ({ ...f, type: t, category: '' }))}
                className={`flex-1 flex items-center justify-center gap-1.5 py-2 rounded-lg text-sm font-medium transition-all ${form.type === t ? 'bg-white shadow text-gray-900' : 'text-gray-500 hover:text-gray-700'}`}>
                {t === 'INCOME' ? <TrendingUp size={13} className="text-green-600" /> : <TrendingDown size={13} className="text-red-500" />}
                {TYPE_LABELS[t]}
              </button>
            ))}
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs font-medium text-gray-600 block mb-1">Categoria</label>
              <select className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm bg-white"
                value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}>
                <option value="">Seleccionar...</option>
                {categories.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
            <Input label="Valor (Kz)" type="number" value={form.amount}
              onChange={e => setForm(f => ({ ...f, amount: e.target.value }))} placeholder="0" />
          </div>

          <Input label="Descrição" value={form.description}
            onChange={e => setForm(f => ({ ...f, description: e.target.value }))}
            placeholder="Ex: Pagamento de quotas de Janeiro" />

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs font-medium text-gray-600 block mb-1">Data</label>
              <input type="date" className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm bg-white"
                value={form.date} onChange={e => setForm(f => ({ ...f, date: e.target.value }))} />
            </div>
            <Input label="Referência (opcional)" value={form.reference}
              onChange={e => setForm(f => ({ ...f, reference: e.target.value }))}
              placeholder="Nº transferência, recibo..." />
          </div>

          <div>
            <label className="text-xs font-medium text-gray-600 block mb-1">Notas (opcional)</label>
            <textarea className="w-full border border-gray-200 rounded-xl px-3 py-2.5 text-sm resize-none" rows={2}
              value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))} />
          </div>

          <div className="flex gap-3 justify-end pt-2">
            <Button variant="secondary" onClick={closeModal}>Cancelar</Button>
            <Button
              onClick={() => editing ? updateMutation.mutate() : createMutation.mutate()}
              loading={createMutation.isPending || updateMutation.isPending}
              disabled={!form.category || !form.amount || !form.description}
            >
              {editing ? 'Guardar' : 'Registar'}
            </Button>
          </div>
        </div>
      </Modal>

      {/* Modal detalhe de lançamento automático */}
      <Modal open={!!detailTx} onClose={() => setDetailTx(null)} title="Detalhe do lançamento">
        {detailTx && (
          <div className="space-y-4">
            <div>
              <p className="text-xs text-gray-500 mb-0.5">Descrição</p>
              <p className="text-sm font-medium text-gray-900">{detailTx.description}</p>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <p className="text-xs text-gray-500 mb-0.5">Valor</p>
                <p className={`text-sm font-bold ${detailTx.type === 'INCOME' ? 'text-green-600' : 'text-red-500'}`}>
                  {detailTx.type === 'INCOME' ? '+' : '-'}{fmtKz(detailTx.amount)}
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-500 mb-0.5">Data</p>
                <p className="text-sm text-gray-900">{fmt(detailTx.date)}</p>
              </div>
            </div>
            {detailTx.member && (
              <div>
                <p className="text-xs text-gray-500 mb-0.5">Membro</p>
                <p className="text-sm text-gray-900">{detailTx.member.nickname ?? detailTx.member.fullName}</p>
              </div>
            )}
            {detailTx.reference && (
              <div>
                <p className="text-xs text-gray-500 mb-0.5">Referência</p>
                <p className="text-sm text-gray-900">{detailTx.reference}</p>
              </div>
            )}
            {detailTx.notes && (
              <div>
                <p className="text-xs text-gray-500 mb-0.5">Notas</p>
                <p className="text-sm text-gray-900">{detailTx.notes}</p>
              </div>
            )}
            {detailTx.sourceRef && (
              <div className="pt-3 border-t border-gray-100">
                {detailTx.sourceRef.startsWith('FINE:') && (
                  <Button variant="secondary" onClick={() => { setDetailTx(null); navigate('/disciplinary') }}>
                    <ExternalLink size={13} /> Ver multa associada
                  </Button>
                )}
                {detailTx.sourceRef.startsWith('QUOTA:') && (
                  <Button variant="secondary" onClick={() => { setDetailTx(null); navigate('/quotas') }}>
                    <ExternalLink size={13} /> Ver quota associada
                  </Button>
                )}
              </div>
            )}
          </div>
        )}
      </Modal>

      {/* Modal saldo inicial */}
      <Modal open={showBalanceModal} onClose={() => setShowBalanceModal(false)} title="Definir saldo inicial do caixa">
        <div className="space-y-4">
          <p className="text-sm text-gray-500">
            O saldo inicial é o valor em caixa antes de qualquer movimento registado no sistema.
            Inclui-se no cálculo do saldo total.
          </p>
          <Input
            label="Saldo inicial (Kz)"
            type="number"
            value={balanceInput}
            onChange={e => setBalanceInput(e.target.value)}
            placeholder="0"
          />
          <div className="flex gap-3 justify-end pt-1">
            <Button variant="secondary" onClick={() => setShowBalanceModal(false)}>Cancelar</Button>
            <Button
              onClick={() => balanceMutation.mutate()}
              loading={balanceMutation.isPending}
              disabled={balanceInput === '' || isNaN(parseFloat(balanceInput))}
            >
              Guardar
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  )
}
