import { Router, Response } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma'
import { authenticate, requirePermission, AuthRequest } from '../middleware/auth'

const router = Router()
router.use(authenticate)

const INCOME_CATEGORIES  = ['Quotas', 'Multas', 'Patrocínio', 'Evento', 'Doação', 'Outro']
const EXPENSE_CATEGORIES = ['Equipamento', 'Combustível', 'Alojamento', 'Refeições', 'Manutenção', 'Administrativo', 'Evento', 'Outro']

const memberSelect = { fullName: true, nickname: true, memberNumber: true }

async function getInitialBalance(clubId: string): Promise<number> {
  const club = await prisma.club.findUnique({ where: { id: clubId }, select: { defaultSettings: true } })
  const s = (club?.defaultSettings ?? {}) as Record<string, any>
  return typeof s.treasuryInitialBalance === 'number' ? s.treasuryInitialBalance : 0
}

// GET /api/treasury — listar transacções (com filtros)
router.get('/', async (req: AuthRequest, res: Response) => {
  const { type, category, year, month } = req.query as Record<string, string>

  const startOf = (y: number, m?: number) => new Date(y, m !== undefined ? m - 1 : 0, 1)
  const endOf   = (y: number, m?: number) => m !== undefined
    ? new Date(y, m, 0, 23, 59, 59, 999)
    : new Date(y, 11, 31, 23, 59, 59, 999)

  const gte = year ? startOf(+year, month ? +month : undefined) : undefined
  const lte = year ? endOf(+year, month ? +month : undefined) : undefined

  const [transactions, initialBalance] = await Promise.all([
    prisma.transaction.findMany({
      where: {
        clubId: req.user!.clubId,
        ...(type && { type: type as any }),
        ...(category && { category }),
        ...(gte && lte && { date: { gte, lte } }),
      },
      include: { member: { select: memberSelect } },
      orderBy: { date: 'desc' },
    }),
    getInitialBalance(req.user!.clubId),
  ])

  const totalIncome  = transactions.filter(t => t.type === 'INCOME').reduce((s, t) => s + t.amount, 0)
  const totalExpense = transactions.filter(t => t.type === 'EXPENSE').reduce((s, t) => s + t.amount, 0)

  return res.json({
    transactions,
    initialBalance,
    totalIncome,
    totalExpense,
    balance: initialBalance + totalIncome - totalExpense,
  })
})

// GET /api/treasury/categories
router.get('/categories', (_req, res) => {
  return res.json({ income: INCOME_CATEGORIES, expense: EXPENSE_CATEGORIES })
})

// PATCH /api/treasury/initial-balance — definir saldo inicial do caixa
router.patch('/initial-balance', requirePermission('TREASURY'), async (req: AuthRequest, res: Response) => {
  try {
    const { amount } = z.object({ amount: z.number().min(0) }).parse(req.body)
    const club = await prisma.club.findUnique({ where: { id: req.user!.clubId }, select: { defaultSettings: true } })
    const settings = (club?.defaultSettings ?? {}) as Record<string, any>
    await prisma.club.update({
      where: { id: req.user!.clubId },
      data: { defaultSettings: { ...settings, treasuryInitialBalance: amount } },
    })
    return res.json({ initialBalance: amount })
  } catch (err) {
    if (err instanceof z.ZodError) return res.status(400).json({ error: err.errors })
    throw err
  }
})

// POST /api/treasury — criar transacção manual
router.post('/', requirePermission('TREASURY'), async (req: AuthRequest, res: Response) => {
  try {
    const data = z.object({
      type:        z.enum(['INCOME', 'EXPENSE']),
      category:    z.string().min(1),
      amount:      z.number().positive(),
      description: z.string().min(1),
      reference:   z.string().nullish(),
      date:        z.string().default(() => new Date().toISOString()),
      memberId:    z.string().nullish(),
      notes:       z.string().nullish(),
    }).parse(req.body)

    const tx = await prisma.transaction.create({
      data: {
        clubId:      req.user!.clubId,
        type:        data.type,
        category:    data.category,
        amount:      data.amount,
        description: data.description,
        reference:   data.reference ?? null,
        date:        new Date(data.date),
        memberId:    data.memberId ?? null,
        createdById: req.user!.userId,
        notes:       data.notes ?? null,
        autoGenerated: false,
      },
      include: { member: { select: memberSelect } },
    })
    return res.status(201).json(tx)
  } catch (err) {
    if (err instanceof z.ZodError) return res.status(400).json({ error: err.errors })
    throw err
  }
})

// PATCH /api/treasury/:id — editar transacção (só manuais)
router.patch('/:id', requirePermission('TREASURY'), async (req: AuthRequest, res: Response) => {
  try {
    const tx = await prisma.transaction.findFirst({ where: { id: req.params.id, clubId: req.user!.clubId } })
    if (!tx) return res.status(404).json({ error: 'Transacção não encontrada' })
    if (tx.autoGenerated) return res.status(403).json({ error: 'Não é possível editar transacções geradas automaticamente.' })

    const data = z.object({
      type:        z.enum(['INCOME', 'EXPENSE']).optional(),
      category:    z.string().min(1).optional(),
      amount:      z.number().positive().optional(),
      description: z.string().min(1).optional(),
      reference:   z.string().nullish(),
      date:        z.string().optional(),
      memberId:    z.string().nullish(),
      notes:       z.string().nullish(),
    }).parse(req.body)

    const updated = await prisma.transaction.update({
      where: { id: tx.id },
      data: {
        ...data,
        date:     data.date ? new Date(data.date) : undefined,
        memberId: data.memberId ?? null,
      },
      include: { member: { select: memberSelect } },
    })
    return res.json(updated)
  } catch (err) {
    if (err instanceof z.ZodError) return res.status(400).json({ error: err.errors })
    throw err
  }
})

// DELETE /api/treasury/:id (só manuais)
router.delete('/:id', requirePermission('TREASURY'), async (req: AuthRequest, res: Response) => {
  const tx = await prisma.transaction.findFirst({ where: { id: req.params.id, clubId: req.user!.clubId } })
  if (!tx) return res.status(404).json({ error: 'Transacção não encontrada' })
  if (tx.autoGenerated) return res.status(403).json({ error: 'Não é possível eliminar transacções geradas automaticamente. Elimina o pagamento de quota correspondente.' })
  await prisma.transaction.delete({ where: { id: tx.id } })
  return res.status(204).send()
})

export default router

// ── função utilitária usada por outras rotas ────────────────────────────────
export async function createQuotaTransaction(p: {
  clubId: string
  memberId: string
  memberName: string
  amount: number
  year: number
  paymentId: string
  paidAt: Date
  createdById: string
}) {
  return prisma.transaction.create({
    data: {
      clubId:        p.clubId,
      type:          'INCOME',
      category:      'Quotas',
      amount:        p.amount,
      description:   `Quota ${p.year} — ${p.memberName}`,
      date:          p.paidAt,
      memberId:      p.memberId,
      createdById:   p.createdById,
      autoGenerated: true,
      sourceRef:     `QUOTA:${p.paymentId}`,
    },
  })
}

export async function deleteQuotaTransaction(paymentId: string, clubId: string) {
  await prisma.transaction.deleteMany({
    where: { sourceRef: `QUOTA:${paymentId}`, clubId },
  })
}
